Repository scaleapi/llm-engine, pull requests merged in 2023-08, with the labels that each got.

#220 Add readme to model-engine folder
  model-engine/README.md
Labels: documentation

#219 Add pre-commit hooks for mypy, semgrep, and trufflehog
  .pre-commit-config.yaml
Labels: dependencies

#225 Fix API calls on Windows
  clients/python/llmengine/__init__.py
  clients/python/llmengine/api_engine.py
  clients/python/pyproject.toml
  clients/python/setup.py
Labels: bug, good first issue

#231 add file upload guidance to fine-tune docs
  clients/python/llmengine/fine_tuning.py
  docs/guides/fine_tuning.md
Labels: documentation

#238 add peft config documentation
  clients/python/llmengine/fine_tuning.py
  docs/guides/fine_tuning.md
Labels: documentation
